"""initial schema

Revision ID: 8f98a3b5cfe9
Revises: 
Create Date: 2026-09-09 13:46:27.257356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f98a3b5cfe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='admin_status'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_type', sa.Enum('admin', 'client', name='audit_user_type'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('clients',
    sa.Column('client_uuid', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('download_password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='client_status'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('folder_uid', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_uid')
    )
    op.create_index(op.f('ix_clients_client_uuid'), 'clients', ['client_uuid'], unique=True)
    op.create_table('albums',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('album_uuid', sa.String(length=36), nullable=False),
    sa.Column('album_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='album_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('folder_uid', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_uid')
    )
    op.create_index(op.f('ix_albums_album_uuid'), 'albums', ['album_uuid'], unique=True)
    op.create_index(op.f('ix_albums_client_id'), 'albums', ['client_id'], unique=False)
    op.create_index(op.f('ix_albums_expires_at'), 'albums', ['expires_at'], unique=False)
    op.create_table('sessions',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_client_id'), 'sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_session_token_hash'), 'sessions', ['session_token_hash'], unique=True)
    op.create_table('download_jobs',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'preparing', 'processing', 'completed', 'failed', 'expired', name='download_job_status'), nullable=False),
    sa.Column('media_ids_json', sa.Text(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('completed_files', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('completed_bytes', sa.BigInteger(), nullable=False),
    sa.Column('zip_path', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by_type', sa.Enum('admin', 'client', name='download_job_requester_type'), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_jobs_album_id'), 'download_jobs', ['album_id'], unique=False)
    op.create_index(op.f('ix_download_jobs_client_id'), 'download_jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_download_jobs_expires_at'), 'download_jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_download_jobs_status'), 'download_jobs', ['status'], unique=False)
    op.create_table('media',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Enum('photo', 'video', name='media_file_type'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('google_drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='media_status'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_album_id'), 'media', ['album_id'], unique=False)
    op.create_index(op.f('ix_media_client_id'), 'media', ['client_id'], unique=False)
    op.create_index(op.f('ix_media_file_uuid'), 'media', ['file_uuid'], unique=True)
    op.create_table('upload_sessions',
    sa.Column('upload_id', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('bytes_uploaded', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'uploading', 'completed', 'failed', 'cancelled', name='upload_session_status'), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'upload_id', name='uq_upload_session_admin_upload')
    )
    op.create_index(op.f('ix_upload_sessions_admin_id'), 'upload_sessions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_album_id'), 'upload_sessions', ['album_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_status'), 'upload_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_upload_sessions_upload_id'), 'upload_sessions', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_sessions_upload_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_status'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_album_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_admin_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_index(op.f('ix_media_file_uuid'), table_name='media')
    op.drop_index(op.f('ix_media_client_id'), table_name='media')
    op.drop_index(op.f('ix_media_album_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_download_jobs_status'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_expires_at'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_client_id'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_album_id'), table_name='download_jobs')
    op.drop_table('download_jobs')
    op.drop_index(op.f('ix_sessions_session_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_client_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_albums_expires_at'), table_name='albums')
    op.drop_index(op.f('ix_albums_client_id'), table_name='albums')
    op.drop_index(op.f('ix_albums_album_uuid'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_clients_client_uuid'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
